name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pandas-profiling
  - path.py
  - python=3.8
  - scikit-learn
  - seaborn
  - statsmodels
  - pip:
      - black
      - h2o
      - streamlit
      - keras
      - lightgbm
      - missingno
      - nbdime
      - plotly
      - flake8
      - pyspark
      - tensorflow
